# Numpy

## NumPy 기초

In [2]:
import numpy as np

In [2]:
data = np.random.randn(2,3)   # 표준 정규분포에서 샘플링한 난수를 출력해주는 것
data

array([[-0.08714918,  0.36653446,  1.63394732],
       [ 0.7468592 , -0.2417934 ,  0.44362765]])

In [3]:
data * 10

array([[-0.87149182,  3.66534461, 16.33947321],
       [ 7.46859203, -2.41793402,  4.4362765 ]])

In [4]:
data + data

array([[-0.17429836,  0.73306892,  3.26789464],
       [ 1.49371841, -0.4835868 ,  0.8872553 ]])

In [5]:
data.shape           # 각 차원의 크기를 알려주는 shape  2차원이고 각 차원의 배열 길이는 3이다.

(2, 3)

In [6]:
data.dtype          # 배열에 저장된 자료형을 알려주는 dtype

dtype('float64')

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)          # data1을 arr1이라는 배열로 만들어주는 것
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1,2,3,4], [5,6,7,8]]      # 같은 길이를 가지는 리스트를 내포하고 있으면 다차원 배열로 변환 가능

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim              # 차원의 수를 알려줌

2

In [10]:
arr2.shape            # 각 차원의 배열의 길이까지 알려줌 

(2, 4)

In [11]:
arr1.dtype             

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

In [13]:
np.zeros(10)                 # 주어진 길이나 모양에 각각 0이 들어있는 배열을 생성하는 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,6))             # 3차원 6배열을 다 0으로 만들어줌 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,3))             # 2차원 벡터

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((2,3,2))            # 정육면체 3차원 벡터 

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
np.zeros((2,3,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [18]:
np.arange(15)         # 자료형을 명시하지 않으면 float가 된다. 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.empty((3,5))           # 쓰레기값들 채워줌 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)
arr1
arr2

array([1, 2, 3])

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [8]:
arr = np.array([1,2,3,4,5])
arr
arr.dtype

dtype('int32')

In [24]:
float_arr = arr.astype(np.float64)       #astype는 기존 배열의 dtype를 다른 형으로 변환 해줌 
float_arr                                #정수형 원소들을 실수로 바꿔줌 

array([1., 2., 3., 4., 5.])

In [25]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [26]:
arr.astype(np.int32)                 # 실수를 다 정수로 바꿔줌 

array([ 3, -1, -2,  0, 12, 10])

In [27]:
numeric_strings = np.array(['1.25', '-9.6', '42' ], dtype=np.string_)
numeric_strings.dtype

dtype('S4')

In [28]:
numeric_strings     # 여기서 b가 뭘까? 쌤도 모름

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [29]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [30]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)    # int_array를 calibers의 형으로 형변환해준 것 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
empty_uint32 = np.empty(8, dtype = 'u4')

empty_uint32              # uint32는 0~255까지 부호없는 정수형 표현 가능

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

## NumPy 배열의 산술연산

In [32]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
arr * arr         # 와 그냥 연산이 된다... numpy 개꿀

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [34]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [35]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [38]:
arr2 > arr             # 같은 크기를 가지는 배열 간의 비교 연산은 불리언 배열을 반환 , 생각보다 많이 씀

array([[False,  True, False],
       [ True, False,  True]])

## 색인과 슬라이싱 기초

In [39]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[5]

5

In [41]:
arr[5:8]

array([5, 6, 7])

In [42]:
arr[5:8] = 12          # 6번째부터 8번째까지 12를 추가한다

In [43]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [44]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [45]:
arr_slice[1] = 12345
arr            # arr의 값도 바뀜

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [46]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [47]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr2d[2]

array([7, 8, 9])

In [48]:
arr2d[0][2]       # arr2d의 0번째에서 3번째 꺼를 반환해라     # 0번축을 로우, 1번축을 컬럼

3

In [49]:
arr2d[0, 2]

3

In [50]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0]                 # arr3d[0]은 2x3 크기의 배열이다

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
old_values = arr3d[0].copy()      #arr3d의 복사본

arr3d[0] = 42

In [53]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[0] = old_values    # 기존꺼 복사되어 있지 개신기

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[1,0]

array([7, 8, 9])

In [56]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [57]:
x[0]

array([7, 8, 9])

## 슬라이스로 선택하기

In [58]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [59]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [60]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [63]:
arr2d[1, :2]

array([4, 5])

In [64]:
arr2d[:2, 2]

array([3, 6])

In [65]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [66]:
arr2d[:2, 1:] = 0

arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

 ## 불리언 값으로 선택하기

In [67]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [68]:
data

array([[ 0.21121647,  1.70687366, -0.68882669, -0.04241165],
       [-2.13187831, -0.29723069,  2.27017021, -0.4587503 ],
       [ 0.63916213, -0.71380491, -0.90825517,  1.51768318],
       [ 0.3125664 , -0.8983231 ,  0.50149479,  1.18603503],
       [ 0.09724532, -1.26439168,  1.28932927, -0.16347352],
       [-0.06659872,  0.39749356,  0.82916024,  1.53096162],
       [ 1.41628991, -0.6617486 , -1.56622769, -0.76875691]])

In [69]:
names =='Bob'         # Bob인 애들만 True 나머지 False, 각각의 이름은 data 배열의 각 로우와 대응

array([ True, False, False,  True, False, False, False])

In [70]:
data[names == 'Bob']      # 불리언 배열은 색인하려는 축의 길이와 같아야함, 그렇지 않으면 나머지는 삭제함

array([[ 0.21121647,  1.70687366, -0.68882669, -0.04241165],
       [ 0.3125664 , -0.8983231 ,  0.50149479,  1.18603503]])

In [71]:
data[names == 'Bob', 2:]   # names =='Bob' 인 로우에서 2: 컬럼을 선택했다. 

array([[-0.68882669, -0.04241165],
       [ 0.50149479,  1.18603503]])

In [72]:
data[names == 'Bob', 3]

array([-0.04241165,  1.18603503])

In [73]:
names !='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [74]:
data[~(names == 'Bob')]        ~ 를 사용하면 조건절 부인을 의미함, 

SyntaxError: invalid syntax (<ipython-input-74-28161e29e878>, line 1)

In [ ]:
cond = names =='Bob'

data[~cond]

In [ ]:
mask = (names == 'Bob') | (names== 'Will')    # |은 or임 , &가 and
mask

In [ ]:
data[mask]

In [ ]:
data[data<0] =0          # 이런것도 된다...
data

In [ ]:
# 1차원 불리언 배열을 사용해서 전체 로우나 컬럼을 선택하는걸 쉽게 할 수 있음, 2차원은 pandas로!

In [ ]:
arr = np.empty((8,4))
arr

In [ ]:
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[[4,3,0,6]]         # 5번째, 3번째 첫번째 6번째를 불러온다

In [ ]:
arr = np.arange(32).reshape((8,4))  32까지 8차원 4배열로!
arr

In [ ]:
arr[[1,5,7,2], [0,3,1,2]] # (1,0), (5,3), (7,1), (2,2)에 대응하는 원소들을 배열해라 

In [ ]:
arr= np.arange(15).reshape((3,5))
arr

In [ ]:
a = arr.T                   #축을 바꾸는 것 
a

In [ ]:
a.T

## 유니버설 함수

In [ ]:
arr = np.arange(10)
arr

In [ ]:
np.sqrt(arr)               # arr 배열의 원소들을 루트 씌워라

In [ ]:
np.exp(arr)                # arr 배열의 원소들을 e 이거 해줘라

In [ ]:
x = np.random.randn(8)
y = np.random.randn(8)

np.maximum(x,y)               # x와 y배열의 각 원소들을 비교했을 때 큰 값들만 가져옴

In [ ]:
arr = np.random.randn(7)*5
arr

In [ ]:
remainder, whole_part = np.modf(arr)    # modf는 분수를 받아서 몫과 나머지를 반환함

In [ ]:
remainder                     # 나머지를 remainder에

In [ ]:
whole_part         # 몫을 whole_part에다가!

In [ ]:
p = np.arange(-5, 5, 0.01)     # -5부터 5까지 0.01씩 증가하는 값들의 배열 

where

result = np.where(cond, xarr, yarr)   # cond가 True일때는 xarr을 그렇지 않을때는 yarr값을 반환

In [ ]:
#  Ex)  np.where(arr > 0, 2, arr)   arr이 양수면 2를 대입하고 그렇지 않으면 그대로

## 수학 메서드, 통계 메서드

In [ ]:
arr = np.random.randn(5,4)
arr

In [ ]:
arr.mean()

In [ ]:
np.mean(arr)            # 위에랑 똑같음

In [ ]:
arr.sum()

In [ ]:
arr.mean(axis=1)            # 각 행의 평균, 컬럼의 평균

In [ ]:
arr.sum(axis=0)             # 각 열의 합, 로우의 합

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7])
arr.cumsum()                       # 누적 합을 의미

In [ ]:
arr=np.array([[0,1,2], [3,4,5], [6,7,8]])

In [ ]:
arr.cumsum(axis=0)             # 행의 누적 합 

## 정렬

In [ ]:
arr = np.random.randn(6)
arr

In [ ]:
arr.sort()
arr

In [ ]:
arr=np.random.randn(5,3)
arr

In [ ]:
arr.sort(1)              # 1차원 부분을 정렬하는 것, 행을 정렬하는 것
arr

집합 관련 함수

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Will', 'Joe'])
np.unique(names)         # unique는 배열중 중복된 원소를 제거하고 남은 원소를 정렬된 형태로 반환 

In [ ]:
values = np.array([6,0,0,3,2,5,6])

np.in1d(values, [2,3,6])   # in1d 함수는 첫번째 배여의 원소가 두번째 배열의 원소를 포함하는지 불리언 형태로 반환

## 배열 데이터 파일 입출력

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)       # some_array 가 npy 형태로 저장되어 있음, 안의 내용은 arr

In [ ]:
np.load('some_array.npy')        # load는 파일을 불러옴 

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)   # savez는 압축된 형식으로 저장 할 수 있음

In [ ]:
arch = np.load('array_archive.npz')

arch['b']

In [ ]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

# Pandas

## Panda 기초

In [9]:
import pandas as pd    # 판다스 꾸러미 전체를 pd라는 이름으로 가져온다

In [ ]:
from pandas import Series, DataFrame   # 시리즈랑 데이터 프레임만 가져온다

In [10]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [11]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [12]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [13]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [15]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [ ]:
obj2[obj2>0]

In [ ]:
# 딕셔너리형에 데이터를 시리즈로 저장 가능

In [16]:
sdata ={'Ohio': 35000, 'Texas' : 71000, 'Oregon': 16000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
dtype: int64

In [18]:
states = ['California', 'Ohio', 'Oregon']

obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
dtype: float64

## 판다스에서 누락된 또는 NaN 데이터를 찾을 때 쓰는 함수

In [19]:
pd.isnull(obj4)      # null 값 있는지 찾아내는 것 

California     True
Ohio          False
Oregon        False
dtype: bool

In [ ]:
pd.notnull(obj4)

In [20]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
dtype: bool

In [ ]:
obj3      

In [ ]:
obj4

In [ ]:
obj3 + obj4        # 시리즈에서는 산술 연산 시 색인과 라벨로 자동 정렬함

In [ ]:
obj4.name = 'population'
obj4.index.name = 'state'

obj4

In [ ]:
obj

In [ ]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']   # 인덱스를 대입하여 변경 가능
obj

## DataFrame

In [24]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
frame.head()       # head는 처음 5개의 로우만 출력시켜줌

In [25]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])   # 원하는 순서대로 컬럼 생성

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [27]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2        # 사전에 없는 값을 넘기면 결측치로 저장된다.

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [28]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [29]:
frame2['state']        

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2.state

In [ ]:
frame2.year

In [30]:
frame2.loc['three']        # 로우는 위치나 loc 속성을 이용해서 이름을 통해 접근할 수 있음

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [31]:
frame2['debt'] = 16.5    # 비어있는 debt 컬럼에 스칼라 값이나 배열의 값을 대입할 수 있음 
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [32]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [33]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

frame2['debt'] = val

frame2                 # 리스트나 배열을 컬럼에 대입할 때 대입하려는 값의 길이가 DataFrame이랑 동일해야함
                # Series를 대입하면 DataFrame의 색인에 따라 값이 대입되면 존재하지 않는 색인은 결측치

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [ ]:
frame2['eastern'] = frame2.state == 'Ohio' 

frame2

In [ ]:
del frame2['eastern']     # 지우기
frame2

In [34]:
pop = {'Nevada': {2001: 2.4, 2002:2.9}, 'Ohio': {2000:1.5, 2001:1.7, 2002:3.6}}

# 바깥에 있는 키(Nevada, Ohio)는 DataFrame의 컬럼이 되고 안에 있는 키는 로우가 된다

In [35]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [36]:
frame3.T    # 컬럼과 로우를 뒤집기

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [ ]:
pd.DataFrame(pop, index=[2001,2002,2003])       # pop을 불러오면서 색인을 직접 지정 

## 재색인

In [37]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])

obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [38]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])      # reindex는 새로운 색인에 맞게 재배열하고 결측치 추가
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [39]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [40]:
obj3.reindex(range(6), method='ffill')   #ffill메서드는 누락된값을 직전의 값으로 채워 넣을 수 있음

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

## 하나의 로우나 컬럼 삭제하기

In [ ]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

In [ ]:
new_obj = obj.drop('c')    # c행을 없애 버림
new_obj

In [ ]:
obj.drop(['d', 'c'])   #c와 d행을 없애버림

In [41]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])  
# reshape는()대로 프레임을 만들어 주는 듯
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop(['Colorado', 'Ohio'])   # 콜로라도와 오하이오의 해당 로우 값을 다 삭제한다.

## 실습

In [42]:
%conda install pandas-datareader

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np
from pandas_datareader import data

In [3]:
df =data.get_data_yahoo('005930.KS', "2020-01-01")

In [4]:
df

High      Low     Open    Close      Volume     Adj Close
Date                                                                    
2020-01-02  56000.0  55000.0  55500.0  55200.0  12993228.0  52537.179688
2020-01-03  56600.0  54900.0  56000.0  55500.0  15422255.0  52822.707031
2020-01-06  55600.0  54600.0  54900.0  55500.0  10278951.0  52822.707031
2020-01-07  56400.0  55600.0  55700.0  55800.0  10009778.0  53108.238281
2020-01-08  57400.0  55900.0  56200.0  56800.0  23501171.0  54059.992188
...             ...      ...      ...      ...         ...           ...
2021-05-31  80600.0  79600.0  80300.0  80500.0  13321324.0  80500.000000
2021-06-01  81300.0  80100.0  80500.0  80600.0  14058401.0  80600.000000
2021-06-02  81400.0  80300.0  80400.0  80800.0  16414644.0  80800.000000
2021-06-03  83000.0  81100.0  81300.0  82800.0  29546007.0  82800.000000
2021-06-04  82700.0  81500.0  82700.0  82200.0  18042798.0  82200.000000

[353 rows x 6 columns]

In [5]:
df.head()

High      Low     Open    Close      Volume     Adj Close
Date                                                                    
2020-01-02  56000.0  55000.0  55500.0  55200.0  12993228.0  52537.179688
2020-01-03  56600.0  54900.0  56000.0  55500.0  15422255.0  52822.707031
2020-01-06  55600.0  54600.0  54900.0  55500.0  10278951.0  52822.707031
2020-01-07  56400.0  55600.0  55700.0  55800.0  10009778.0  53108.238281
2020-01-08  57400.0  55900.0  56200.0  56800.0  23501171.0  54059.992188

### close 컬럼 삭제

In [6]:
df.drop('Close', axis=1)  1번

SyntaxError: invalid syntax (<ipython-input-6-89f9381a0c9a>, line 1)

### 컬럼명을 한국어로 바꾸기

### 상위 3개만 선택해서 출력

In [7]:
df.head(3)        # 3번

High      Low     Open    Close      Volume     Adj Close
Date                                                                    
2020-01-02  56000.0  55000.0  55500.0  55200.0  12993228.0  52537.179688
2020-01-03  56600.0  54900.0  56000.0  55500.0  15422255.0  52822.707031
2020-01-06  55600.0  54600.0  54900.0  55500.0  10278951.0  52822.707031

### 종가(Adj close)데이터 뽑기

In [8]:
df.loc['High','2020-01-02']       # 4번

KeyError: 'High'

### 2021년 1월 15일의 데이터

### 시작가 대비 종가가 높았던 날의 데이터

In [10]:
df[df['Adj Close'] > df['Open']]

High      Low     Open    Close      Volume     Adj Close
Date                                                                    
2020-03-13  51600.0  46850.0  47450.0  49950.0  59462933.0  47540.437500
2020-03-24  46950.0  43050.0  43850.0  46950.0  49801908.0  44685.156250
2020-06-03  55000.0  51700.0  51800.0  54500.0  49257814.0  52253.925781
2020-11-13  63200.0  61000.0  61300.0  63200.0  31508829.0  61375.773438
2020-11-16  66700.0  63900.0  64000.0  66300.0  36354334.0  64386.292969
2020-11-23  67800.0  64700.0  64800.0  67500.0  27134398.0  65551.656250
2020-12-24  78800.0  74000.0  74100.0  77800.0  32502870.0  75554.351562
2020-12-30  81300.0  77300.0  77400.0  81000.0  29417421.0  80641.656250
2021-01-04  84400.0  80200.0  81000.0  83000.0  38655276.0  82632.804688
2021-01-05  83900.0  81600.0  81600.0  83900.0  35335669.0  83528.820312
2021-01-08  90000.0  83000.0  83300.0  88800.0  59013307.0  88407.148438
2021-01-11  96800.0  89500.0  90000.0  91000.0  90306177.0  90597.414062
2021-01-14  90000.0  88700.0  88700.0  89700.0  26393970.0  89303.164062
2021-01-19  88000.0  83600.0  84500.0  87000.0  39895044.0  86615.109375
2021-01-21  88600.0  86500.0  87500.0  88100.0  25318011.0  87710.242188
2021-01-25  89900.0  86300.0  87000.0  89400.0  27258534.0  89004.492188
2021-01-28  85600.0  83200.0  83200.0  83700.0  31859808.0  83329.710938
2021-02-01  83400.0  81000.0  81700.0  83000.0  28046832.0  82632.804688
2021-02-05  84000.0  82500.0  83100.0  83500.0  18036835.0  83130.593750
2021-02-15  84500.0  83300.0  83800.0  84200.0  23529706.0  83827.500000
2021-02-16  86000.0  84200.0  84500.0  84900.0  20483100.0  84524.398438
2021-02-23  82900.0  81100.0  81200.0  82000.0  20587314.0  81637.226562
2021-02-25  85400.0  83000.0  84000.0  85300.0  34155986.0  84922.632812
2021-03-03  84000.0  82800.0  83500.0  84000.0  19882132.0  83628.382812
2021-03-05  82600.0  81100.0  81100.0  82100.0  20508971.0  81736.789062
2021-03-11  82500.0  81000.0  81000.0  82000.0  23818297.0  81637.226562
2021-03-16  83000.0  82100.0  82200.0  82800.0  12293537.0  82433.687500
2021-03-30  82300.0  81300.0  81600.0  82200.0  13121698.0  82200.000000
2021-04-01  83000.0  82000.0  82500.0  82900.0  18676461.0  82900.000000
2021-04-02  85200.0  83900.0  84000.0  84800.0  22997538.0  84800.000000
2021-04-13  84500.0  82800.0  83000.0  84000.0  15238206.0  84000.000000
2021-04-15  84500.0  83400.0  83700.0  84100.0  16377412.0  84100.000000
2021-04-20  84000.0  83100.0  83300.0  83900.0  15521965.0  83900.000000
2021-04-23  82900.0  81600.0  81900.0  82800.0  17805080.0  82800.000000
2021-04-26  83500.0  82600.0  82900.0  83500.0  15489938.0  83500.000000
2021-05-03  82400.0  81000.0  81000.0  81700.0  15710336.0  81700.000000
2021-05-04  82600.0  81800.0  81900.0  82600.0  12532550.0  82600.000000
2021-05-06  82300.0  81700.0  81700.0  82300.0  17047511.0  82300.000000
2021-05-07  82100.0  81500.0  81800.0  81900.0  14154882.0  81900.000000
2021-05-10  83500.0  81800.0  82300.0  83200.0  19385027.0  83200.000000
2021-05-14  80300.0  78900.0  79000.0  80100.0  16450920.0  80100.000000
2021-05-20  79700.0  79100.0  79400.0  79500.0  16541828.0  79500.000000
2021-05-28  80400.0  79400.0  79800.0  80100.0  12360199.0  80100.000000
2021-05-31  80600.0  79600.0  80300.0  80500.0  13321324.0  80500.000000
2021-06-01  81300.0  80100.0  80500.0  80600.0  14058401.0  80600.000000
2021-06-02  81400.0  80300.0  80400.0  80800.0  16414644.0  80800.000000
2021-06-03  83000.0  81100.0  81300.0  82800.0  29546007.0  82800.000000

### 종가 기준 주가가 90,000원 이상인 데이터

In [ ]:
df[df['Adj Close'] > 90000]

### 100번째 데이터

## 실습-쌤이 풀어준거

In [91]:
df.head()

High      Low     Open    Close      Volume     Adj Close
Date                                                                    
2020-01-02  56000.0  55000.0  55500.0  55200.0  12993228.0  52537.179688
2020-01-03  56600.0  54900.0  56000.0  55500.0  15422255.0  52822.707031
2020-01-06  55600.0  54600.0  54900.0  55500.0  10278951.0  52822.707031
2020-01-07  56400.0  55600.0  55700.0  55800.0  10009778.0  53108.238281
2020-01-08  57400.0  55900.0  56200.0  56800.0  23501171.0  54059.992188

In [92]:
df.head(3)

High      Low     Open    Close      Volume     Adj Close
Date                                                                    
2020-01-02  56000.0  55000.0  55500.0  55200.0  12993228.0  52537.179688
2020-01-03  56600.0  54900.0  56000.0  55500.0  15422255.0  52822.707031
2020-01-06  55600.0  54600.0  54900.0  55500.0  10278951.0  52822.707031

In [93]:
df.tail()     # 뒤에 5개 가져올 수 있음

High      Low     Open    Close      Volume  Adj Close
Date                                                                 
2021-05-25  80400.0  79800.0  80000.0  79900.0  13628942.0    79900.0
2021-05-26  80500.0  79700.0  80400.0  79800.0  11984359.0    79800.0
2021-05-27  80000.0  79100.0  80000.0  79600.0  23198510.0    79600.0
2021-05-28  80400.0  79400.0  79800.0  80100.0  12360199.0    80100.0
2021-05-31  80600.0  79600.0  80300.0  80500.0  13263445.0    80500.0

In [94]:
df.info()          # 어떤 컬럼이 있고 몇개가 있고, 등등

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 349 entries, 2020-01-02 to 2021-05-31
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   High       349 non-null    float64
 1   Low        349 non-null    float64
 2   Open       349 non-null    float64
 3   Close      349 non-null    float64
 4   Volume     349 non-null    float64
 5   Adj Close  349 non-null    float64
dtypes: float64(6)
memory usage: 19.1 KB


In [95]:
df.describe()           # 수치형 데이터의 주요 초기값을 볼 수 있음 

High           Low          Open         Close        Volume  \
count    349.000000    349.000000    349.000000    349.000000  3.490000e+02   
mean   65438.108883  64018.481375  64702.865330  64697.994269  2.207583e+07   
std    13420.349657  13233.451311  13279.486507  13297.416091  9.843268e+06   
min    43550.000000  42300.000000  42600.000000  42500.000000  0.000000e+00   
25%    55100.000000  54000.000000  54500.000000  54400.000000  1.560453e+07   
50%    60200.000000  59100.000000  59800.000000  59700.000000  1.938503e+07   
75%    81600.000000  80200.000000  81000.000000  81000.000000  2.548310e+07   
max    96800.000000  89500.000000  90300.000000  91000.000000  9.030618e+07   

          Adj Close  
count    349.000000  
mean   63117.763879  
std    14087.749139  
min    40449.824219  
25%    52313.738281  
50%    57139.726562  
75%    80641.656250  
max    90597.414062

0. Close 컬럼 삭제

In [99]:
del df['Close']     
#df.drop('Close', axis='columns', inplace=True)
#df.drop('Close', axis= 1)

KeyError: "['Close'] not found in axis"

In [97]:
df

High      Low     Open      Volume     Adj Close
Date                                                           
2020-01-02  56000.0  55000.0  55500.0  12993228.0  52537.179688
2020-01-03  56600.0  54900.0  56000.0  15422255.0  52822.707031
2020-01-06  55600.0  54600.0  54900.0  10278951.0  52822.707031
2020-01-07  56400.0  55600.0  55700.0  10009778.0  53108.238281
2020-01-08  57400.0  55900.0  56200.0  23501171.0  54059.992188
...             ...      ...      ...         ...           ...
2021-05-25  80400.0  79800.0  80000.0  13628942.0  79900.000000
2021-05-26  80500.0  79700.0  80400.0  11984359.0  79800.000000
2021-05-27  80000.0  79100.0  80000.0  23198510.0  79600.000000
2021-05-28  80400.0  79400.0  79800.0  12360199.0  80100.000000
2021-05-31  80600.0  79600.0  80300.0  13263445.0  80500.000000

[349 rows x 5 columns]

2. 상위 3개 데이터

In [100]:
df[:3]               

High      Low     Open      Volume     Adj Close
Date                                                           
2020-01-02  56000.0  55000.0  55500.0  12993228.0  52537.179688
2020-01-03  56600.0  54900.0  56000.0  15422255.0  52822.707031
2020-01-06  55600.0  54600.0  54900.0  10278951.0  52822.707031

3. 종가 데이터 선택

In [101]:
df['Adj Close']

Date
2020-01-02    52537.179688
2020-01-03    52822.707031
2020-01-06    52822.707031
2020-01-07    53108.238281
2020-01-08    54059.992188
                  ...     
2021-05-25    79900.000000
2021-05-26    79800.000000
2021-05-27    79600.000000
2021-05-28    80100.000000
2021-05-31    80500.000000
Name: Adj Close, Length: 349, dtype: float64

4. 2021년 1월 15일 가져오기

In [102]:
df.loc['2021-01-15']        # 데이터 이름을 가지고 불러오기

High         9.180000e+04
Low          8.800000e+04
Open         8.980000e+04
Volume       3.343181e+07
Adj Close    8.761069e+04
Name: 2021-01-15 00:00:00, dtype: float64

5. 시작가보다 종가가 높았던 날의 데이터

In [103]:
df['Open']<df['Adj Close']

Date
2020-01-02    False
2020-01-03    False
2020-01-06    False
2020-01-07    False
2020-01-08    False
              ...  
2021-05-25    False
2021-05-26    False
2021-05-27    False
2021-05-28     True
2021-05-31     True
Length: 349, dtype: bool

In [112]:
df[df['Open']<df['Adj Close']]

High      Low     Open      Volume     Adj Close
Date                                                           
2020-03-13  51600.0  46850.0  47450.0  59462933.0  47540.437500
2020-03-24  46950.0  43050.0  43850.0  49801908.0  44685.156250
2020-06-03  55000.0  51700.0  51800.0  49257814.0  52253.925781
2020-11-13  63200.0  61000.0  61300.0  31508829.0  61375.773438
2020-11-16  66700.0  63900.0  64000.0  36354334.0  64386.292969
2020-11-23  67800.0  64700.0  64800.0  27134398.0  65551.656250
2020-12-24  78800.0  74000.0  74100.0  32502870.0  75554.351562
2020-12-30  81300.0  77300.0  77400.0  29417421.0  80641.656250
2021-01-04  84400.0  80200.0  81000.0  38655276.0  82632.804688
2021-01-05  83900.0  81600.0  81600.0  35335669.0  83528.820312
2021-01-08  90000.0  83000.0  83300.0  59013307.0  88407.148438
2021-01-11  96800.0  89500.0  90000.0  90306177.0  90597.414062
2021-01-14  90000.0  88700.0  88700.0  26393970.0  89303.164062
2021-01-19  88000.0  83600.0  84500.0  39895044.0  86615.109375
2021-01-21  88600.0  86500.0  87500.0  25318011.0  87710.242188
2021-01-25  89900.0  86300.0  87000.0  27258534.0  89004.492188
2021-01-28  85600.0  83200.0  83200.0  31859808.0  83329.710938
2021-02-01  83400.0  81000.0  81700.0  28046832.0  82632.804688
2021-02-05  84000.0  82500.0  83100.0  18036835.0  83130.593750
2021-02-15  84500.0  83300.0  83800.0  23529706.0  83827.500000
2021-02-16  86000.0  84200.0  84500.0  20483100.0  84524.398438
2021-02-23  82900.0  81100.0  81200.0  20587314.0  81637.226562
2021-02-25  85400.0  83000.0  84000.0  34155986.0  84922.632812
2021-03-03  84000.0  82800.0  83500.0  19882132.0  83628.382812
2021-03-05  82600.0  81100.0  81100.0  20508971.0  81736.789062
2021-03-11  82500.0  81000.0  81000.0  23818297.0  81637.226562
2021-03-16  83000.0  82100.0  82200.0  12293537.0  82433.687500
2021-03-30  82300.0  81300.0  81600.0  13121698.0  82200.000000
2021-04-01  83000.0  82000.0  82500.0  18676461.0  82900.000000
2021-04-02  85200.0  83900.0  84000.0  22997538.0  84800.000000
2021-04-13  84500.0  82800.0  83000.0  15238206.0  84000.000000
2021-04-15  84500.0  83400.0  83700.0  16377412.0  84100.000000
2021-04-20  84000.0  83100.0  83300.0  15521965.0  83900.000000
2021-04-23  82900.0  81600.0  81900.0  17805080.0  82800.000000
2021-04-26  83500.0  82600.0  82900.0  15489938.0  83500.000000
2021-05-03  82400.0  81000.0  81000.0  15710336.0  81700.000000
2021-05-04  82600.0  81800.0  81900.0  12532550.0  82600.000000
2021-05-06  82300.0  81700.0  81700.0  17047511.0  82300.000000
2021-05-07  82100.0  81500.0  81800.0  14154882.0  81900.000000
2021-05-10  83500.0  81800.0  82300.0  19385027.0  83200.000000
2021-05-14  80300.0  78900.0  79000.0  16450920.0  80100.000000
2021-05-20  79700.0  79100.0  79400.0  16541828.0  79500.000000
2021-05-28  80400.0  79400.0  79800.0  12360199.0  80100.000000
2021-05-31  80600.0  79600.0  80300.0  13263445.0  80500.000000

6. 종가가 9만원 이상인 데이터

In [106]:
df[df['Adj Close']>=90000]

High      Low     Open      Volume     Adj Close
Date                                                           
2021-01-11  96800.0  89500.0  90000.0  90306177.0  90597.414062
2021-01-12  91400.0  87800.0  90300.0  48682416.0  90199.179688

7. 100번째 데이터

In [110]:
df.iloc[99]               # 데이터의 자릿수 가지고 가져오기

High         5.120000e+04
Low          4.990000e+04
Open         5.110000e+04
Volume       3.130932e+07
Adj Close    4.832290e+04
Name: 2020-05-28 00:00:00, dtype: float64

1. 이름 바꾸기

In [114]:
df.rename(columns={'High': '고가'})

고가      Low     Open      Volume     Adj Close
Date                                                           
2020-01-02  56000.0  55000.0  55500.0  12993228.0  52537.179688
2020-01-03  56600.0  54900.0  56000.0  15422255.0  52822.707031
2020-01-06  55600.0  54600.0  54900.0  10278951.0  52822.707031
2020-01-07  56400.0  55600.0  55700.0  10009778.0  53108.238281
2020-01-08  57400.0  55900.0  56200.0  23501171.0  54059.992188
...             ...      ...      ...         ...           ...
2021-05-25  80400.0  79800.0  80000.0  13628942.0  79900.000000
2021-05-26  80500.0  79700.0  80400.0  11984359.0  79800.000000
2021-05-27  80000.0  79100.0  80000.0  23198510.0  79600.000000
2021-05-28  80400.0  79400.0  79800.0  12360199.0  80100.000000
2021-05-31  80600.0  79600.0  80300.0  13263445.0  80500.000000

[349 rows x 5 columns]

In [ ]:
# df[3:6] =100        이렇게 하면 해당 내용들이 다 100으로 바뀐다